### ISSUE TITLE
No object detected

### ISSUE THREAD

**Issue by peterturowskij** [DeepRNN/object_detection#1]
Hello Guoming,
thank you very much for sharing this project. I gave it a shot and faced an issue - train phase outputs images (_result, _rois) with nothing detected. Below steps i followed
 
1. git clone
2. git clone coco-master (to recompile it under MacOS)
3. Replace _mask.so with what just compiled.
4. Download The TU Darmstadt Database (formerly the ETHZ Database)
It contains set of **png** images for three classes (car,motorbike,cow). In total **326 images**.
(http://host.robots.ox.ac.uk/pascal/VOC/download/tud.tar.gz).
5. Since annotations there are in "PASCAL Annotation Version 1.00" format i wrote a simple tool to convert into .xml

<img width="1201" alt="vac_format" src="https://cloud.githubusercontent.com/assets/5657810/20648779/2fcc7c94-b4b0-11e6-85af-9147dfadf2fb.png">

6. Prepare directory structure
- models/pascal/vgg16
- train/pascal
  * /images
  * /annotations
- val/pascal
  * /images
  * /annotations
- test/images

7. Start training. I'm running tensorflow cpu only.
`python main.py --phase train --save_period 100 --prepare_anchor_data`
Training results:
`Building the training dataset...`
`Dataset built.`
`Building the basic VGG16 net...`
`Basic VGG16 net built.`
`Building the anchors...`
`Anchor type [35, 70]: 1368 untruncated, 232 truncated`
`Anchor type [50, 50]: 1296 untruncated, 304 truncated`
`Anchor type [70, 35]: 1368 untruncated, 232 truncated`
`Anchor type [70, 141]: 1152 untruncated, 448 truncated`
`Anchor type [100, 100]: 1156 untruncated, 444 truncated`
`Anchor type [141, 70]: 1152 untruncated, 448 truncated`
`Anchor type [141, 282]: 704 untruncated, 896 truncated`
`Anchor type [200, 200]: 784 untruncated, 816 truncated`
`Anchor type [282, 141]: 704 untruncated, 896 truncated`
`Anchor type [212, 424]: 84 untruncated, 316 truncated`
`Anchor type [300, 300]: 100 untruncated, 300 truncated`
`Anchor type [424, 212]: 84 untruncated, 316 truncated`
`Anchor type [282, 565]: 24 untruncated, 376 truncated`
`Anchor type [400, 400]: 64 untruncated, 336 truncated`
`Anchor type [565, 282]: 24 untruncated, 376 truncated`
`Anchor type [353, 707]: 0 untruncated, 400 truncated`
`Anchor type [500, 500]: 16 untruncated, 384 truncated`
`Anchor type [707, 353]: 0 untruncated, 400 truncated`
`Anchors built.`
`Building the RPN...`
`RPN built.`
`Building the RCN...`
`RCN built.`
`Labeling the anchors...`
`100%|████████████████████| 326/326 [00:32<00:00, 10.22it/s]`
`Last iteration`
`loss0=3.531616 loss1=0.032858████████████ | 39/40 [49:40<01:26, 86.39s/it]`
`epoch: 100%|█████████████████| 10/10 [8:26:46<00:00, 3032.09s/it]`
`Model trained.█████████████████████| 40/40 [50:56<00:00, 83.52s/it]`

8. Testing
I put an image into train/pascal/images from a training dataset and converted it into jpg (`dataset.py:347` requirement). Then i ran a command 
`python main.py --phase test`
Upon completion two images (_result, _rois) appeared  in train/pascal/results both with **no objects detected**. 
After debugging i found that **sorted_scores** is full of zeros..

Attaching training log and processed annotations
[train_log.txt](https://github.com/DeepRNN/object_detection/files/614738/train_log.txt)
[annotations.zip](https://github.com/DeepRNN/object_detection/files/614739/annotations.zip)

I would really appreciate if you could help me out.

**Comment by DeepRNN** [comment]
It seems that you did not load the pretrained VGG16 net to initialize the convolutional layers for feature extraction. Currently, my program fixes these layers and only trains the other layers for region proposal and region classification. So initializing these layers with a pretrained model is necessary (otherwise, they are always random and do not produce useful features). To achieve this, you need to use the command line argument "--load_basic_model". 

In addition, your dataset seems really small (compared to the huge neural network you are trying to train), so overfitting might be a serious problem.

**Comment by peterturowskij** [comment]
Oh i see your point, so pretrained model is a must have.

I actually tried to load following:
1) vgg16-20160129.tfmodel (vgg16-20160129.tfmodel.torrent from https://github.com/ry/tensorflow-vgg16)
Running `python main.py --phase train --prepare_anchor_data --load_basic_model --basic_model_file ./tfmodels/vgg16-20160129.tfmodel` 
I get an error
`File "/Users/peter/tensorflow/lib/python2.7/site-packages/numpy/lib/npyio.py", line 416, in load
    "Failed to interpret file %s as a pickle" % repr(file))
IOError: Failed to interpret file './tfmodels/vgg16.tfmodel' as a pickle`

2) vgg16_weights.npz (from https://www.cs.toronto.edu/~frossard/post/vgg16/)
Running `python main.py --phase train --prepare_anchor_data --load_basic_model --basic_model_file ./tfmodels/vgg16_weights.npz`
I get an error
`base_model.py", line 467, in load2
    data_dict = np.load(data_path).item()
AttributeError: 'NpzFile' object has no attribute 'item'`

3. VGG_16.npy (from https://lexiondebug.blob.core.windows.net/mlmodel/models/VGG_16.npy)
Running `python main.py --phase train --prepare_anchor_data --load_basic_model --basic_model_file ./tfmodels/VGG_16.npy` 

Loading completes
`Loading basic model from ./tfmodels/VGG_16.npy...`
`26 variables loaded.`
`**6 variables missed**.`

Shall I ignore this warning on missing variables? If not maybe you could suggest from where to load suitable base model?

I will certainly enrich the dataset, this small one is just to get the first feeling..

**Comment by DeepRNN** [comment]
I obtained the Tensorflow version of VGG16 by using caffe-tensorflow (https://github.com/ethereon/caffe-tensorflow). I think your VGG_16.npy should also work. The missing variables come from the fully-connected layers of VGG16, and you can ignore the warning on them, since we only use the convolutional layers to extract features, and all the fully-connected layers will be retrained.

**Comment by peterturowskij** [comment]
Got it. Let me try run training on that model later today. I will update this thread with results.
Thank you very much for help!

**Comment by DeepRNN** [comment]
You are welcome.

**Comment by peterturowskij** [comment]
Sorry just noticed your edited comment...
I replaced pascal class declarations in **dataset.py** with 
`pascal_num_class = 4`
`pascal_class_names = {0: 'cow', 1: 'car', 2: 'motorbike', 3: 'background'}`
`pascal_class_ids = {'cow': 0, 'car': 1, 'motorbike': 2, 'background': 3} `
`pascal_class_colors = [[189, 149, 122], [138, 241, 227], [171, 113, 234], [152, 248, 224]]`

But i can't find anything hardcoded in **base_model.py** ...

**Comment by DeepRNN** [comment]
In this case, you don't need to change anything in base_model.py. My original suggestion was to add new class declarations for your own dataset in dataset.py, and to change the __init__ method of BaseModel accordingly in base_model.py.

**Comment by peterturowskij** [comment]
It worked! Thanks.
I also trained it on a new class 'yieldsign' (265 images) from (http://guanghan.info/blog/en/my-works/train-yolo/)
`pascal_num_class = 5`
`pascal_class_names = {0: 'cow', 1: 'car', 2: 'motorbike', 3: 'yieldsign', 4: 'background'}`
And results are reasonably good.

FYI: I created ubuntu16 image on Azure to speed up training and with `tensorflow-0.12.0rc0-cp27-none-linux_x86_64` i got a **warning**

`WARNING:tensorflow:From main.py:75 in main.: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use "tf.global_variables_initializer" instead.`

Looking forward to test in on [Azure N-series GPU](https://azure.microsoft.com/en-us/blog/azure-n-series-general-availability-on-december-1/)

**Comment by DeepRNN** [comment]
Glad to hear it. You get the warning because you are using a newer version of tensorflow (my program was based on version r0.11), and google is constantly changing the API.

**Comment by pribadihcr** [comment]
Hi @peterturowskij ,

What GPU type did you use?

**Comment by peterturowskij** [comment]
Hi @pribadihcr ,
I used tensorflow CPU only mode. Haven't tried it on GPU since as for now (as far as I know) no cloud service provides GPU tensorflow will support out of the box and idea is to run it in cloud

**Comment by pribadihcr** [comment]
Hi @peterturowskij,

Great, how was the elapsed time in the inference per image ?
